FROM ubuntu:24.04

RUN apt-get update && apt-get install -y software-properties-common

RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php

RUN apt-get update -y && apt-get install -y apache2

RUN apt-get update -y && apt-get install -y php8.4 \
    libapache2-mod-php8.4 \
    php8.4-common \
    php8.4-mysql \
    php8.4-gmp \
    php8.4-ldap \
    php8.4-curl \
    php8.4-intl \
    php8.4-mbstring \
    php8.4-xmlrpc \
    php8.4-gd \
    php8.4-bcmath \
    php8.4-xml \
    php8.4-cli \
    php8.4-zip
    
RUN a2enmod headers
RUN a2enmod rewrite

RUN wget https://raw.githubusercontent.com/wolxXx/toolz/main/fixPHP.sh && chmod +x fixPHP.sh && ./fixPHP.sh

WORKDIR /var/www

CMD ["apachectl", "-D", "FOREGROUND"]