FROM ubuntu:24.04

RUN apt update && apt install -y  \
    bash-completion  \
    btop  \
    cron  \
    curl  \
    git  \
    htop  \
    inetutils-ping  \
    net-tools  \
    rsync  \
    software-properties-common  \
    tzdata  \
    unzip \
    vim  \
    wget
ENV TZ="Europe/Berlin"

RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php

RUN apt-get update -y && apt-get install -y apache2

RUN apt-get update -y && apt-get install -y php8.2 \
    libapache2-mod-php8.2 \
    php8.2-common \
    php8.2-mysql \
    php8.2-gmp \
    php8.2-ldap \
    php8.2-curl \
    php8.2-intl \
    php8.2-mbstring \
    php8.2-xmlrpc \
    php8.2-gd \
    php8.2-bcmath \
    php8.2-xml \
    php8.2-cli \
    php8.2-zip
    
RUN a2enmod headers
RUN a2enmod rewrite

RUN wget https://raw.githubusercontent.com/wolxXx/toolz/main/fixPHP.sh && chmod +x fixPHP.sh && ./fixPHP.sh

WORKDIR /var/www

CMD ["apachectl", "-D", "FOREGROUND"]