FROM ubuntu:24.04

RUN apt update && apt install -y  \
    bash-completion  \
    btop  \
    cron  \
    curl  \
    git  \
    htop  \
    inetutils-ping  \
    net-tools  \
    rsync  \
    software-properties-common  \
    tzdata  \
    unzip \
    vim  \
    wget
ENV TZ="Europe/Berlin"

RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php

RUN apt-get update -y && apt-get install -y apache2

RUN apt-get update -y && apt-get install -y php8.3 \
    libapache2-mod-php8.3 \
    php8.3-common \
    php8.3-mysql \
    php8.3-gmp \
    php8.3-ldap \
    php8.3-curl \
    php8.3-intl \
    php8.3-mbstring \
    php8.3-xmlrpc \
    php8.3-gd \
    php8.3-bcmath \
    php8.3-xml \
    php8.3-cli \
    php8.3-zip
    
RUN a2enmod headers
RUN a2enmod rewrite

RUN wget https://raw.githubusercontent.com/wolxXx/toolz/main/fixPHP.sh && chmod +x fixPHP.sh && ./fixPHP.sh

WORKDIR /var/www

CMD ["apachectl", "-D", "FOREGROUND"]